export function getData(): any[] {
    return [
        {
            week: 1,
            ekuitas: null,
            rpt: null,
            obligasi: null,
            kas: null,
            rpu: null,
            rdc: null,
            rdp: null,
        },
        {
            week: 2,
            ekuitas: null,
            rpt: null,
            obligasi: 0.66,
            kas: 0.78,
            rpu: 0.58,
            rdc: 0.64,
            rdp: null,
        },
        {
            week: 3,
            ekuitas: 0.58,
            rpt: null,
            obligasi: 0.68,
            kas: 0.7,
            rpu: 0.69,
            rdc: 0.82,
            rdp: null,
        },
        {
            week: 4,
            ekuitas: null,
            rpt: null,
            obligasi: 0.71,
            kas: 0.7,
            rpu: null,
            rdc: 0.82,
            rdp: null,
        },
        {
            week: 5,
            ekuitas: null,
            rpt: null,
            obligasi: null,
            kas: 0.73,
            rpu: 0.79,
            rdc: null,
            rdp: null,
        },
        {
            week: 6,
            ekuitas: null,
            rpt: null,
            obligasi: 0.79,
            kas: 0.78,
            rpu: null,
            rdc: 0.71,
            rdp: null,
        },
        {
            week: 7,
            ekuitas: null,
            rpt: null,
            obligasi: null,
            kas: 0.78,
            rpu: 0.65,
            rdc: 0.76,
            rdp: null,
        },
        {
            week: 8,
            ekuitas: null,
            rpt: null,
            obligasi: 0.79,
            kas: 0.83,
            rpu: 0.36,
            rdc: 0.85,
            rdp: null,
        },
        {
            week: 9,
            ekuitas: null,
            rpt: null,
            obligasi: null,
            kas: 0.84,
            rpu: null,
            rdc: null,
            rdp: null,
        },
        {
            week: 10,
            ekuitas: 0.79,
            rpt: null,
            obligasi: null,
            kas: 0.8,
            rpu: null,
            rdc: 0.74,
            rdp: null,
        },
        {
            week: 11,
            ekuitas: 0.85,
            rpt: null,
            obligasi: null,
            kas: 0.84,
            rpu: null,
            rdc: 0.74,
            rdp: null,
        },
        {
            week: 12,
            ekuitas: 0.88,
            rpt: null,
            obligasi: null,
            kas: 0.9,
            rpu: null,
            rdc: 0.9,
            rdp: null,
        },
        {
            week: 13,
            ekuitas: 0.8,
            rpt: null,
            obligasi: null,
            kas: 0.83,
            rpu: null,
            rdc: 0.83,
            rdp: null,
        },
        {
            week: 14,
            ekuitas: 0.83,
            rpt: null,
            obligasi: 0.61,
            kas: 0.83,
            rpu: null,
            rdc: null,
            rdp: null,
        },
        {
            week: 15,
            ekuitas: 0.74,
            rpt: null,
            obligasi: 0.78,
            kas: 0.8,
            rpu: 0.77,
            rdc: 0.74,
            rdp: null,
        },
        {
            week: 16,
            ekuitas: 0.79,
            rpt: null,
            obligasi: 0.75,
            kas: 0.71,
            rpu: null,
            rdc: 0.8,
            rdp: null,
        },
        {
            week: 17,
            ekuitas: 0.83,
            rpt: null,
            obligasi: 0.71,
            kas: 0.84,
            rpu: null,
            rdc: 0.8,
            rdp: null,
        },
        {
            week: 18,
            ekuitas: 0.83,
            rpt: null,
            obligasi: null,
            kas: 0.92,
            rpu: null,
            rdc: 0.8,
            rdp: null,
        },
        {
            week: 19,
            ekuitas: 0.77,
            rpt: null,
            obligasi: null,
            kas: 0.82,
            rpu: null,
            rdc: 0.78,
            rdp: null,
        },
        {
            week: 20,
            ekuitas: 0.74,
            rpt: null,
            obligasi: 0.76,
            kas: 0.82,
            rpu: null,
            rdc: 0.79,
            rdp: null,
        },
        {
            week: 21,
            ekuitas: 0.74,
            rpt: null,
            obligasi: null,
            kas: 0.82,
            rpu: null,
            rdc: 0.78,
            rdp: null,
        },
        {
            week: 22,
            ekuitas: 0.74,
            rpt: null,
            obligasi: 0.62,
            kas: 0.85,
            rpu: null,
            rdc: 0.77,
            rdp: null,
        },
        {
            week: 23,
            ekuitas: 0.68,
            rpt: null,
            obligasi: 0.78,
            kas: 0.78,
            rpu: null,
            rdc: 0.78,
            rdp: null,
        },
        {
            week: 24,
            ekuitas: null,
            rpt: null,
            obligasi: 0.45,
            kas: 0.81,
            rpu: null,
            rdc: 0.77,
            rdp: null,
        },
        {
            week: 25,
            ekuitas: null,
            rpt: null,
            obligasi: 0.68,
            kas: 0.8,
            rpu: null,
            rdc: 0.55,
            rdp: null,
        },
        {
            week: 26,
            ekuitas: null,
            rpt: null,
            obligasi: 0.71,
            kas: 0.81,
            rpu: null,
            rdc: null,
            rdp: null,
        },
        {
            week: 27,
            ekuitas: null,
            rpt: null,
            obligasi: 0.71,
            kas: 0.74,
            rpu: null,
            rdc: null,
            rdp: 0.53,
        },
        {
            week: 28,
            ekuitas: null,
            rpt: null,
            obligasi: 0.68,
            kas: 0.81,
            rpu: 0.62,
            rdc: 0.29,
            rdp: null,
        },
        {
            week: 29,
            ekuitas: null,
            rpt: null,
            obligasi: 0.66,
            kas: 0.71,
            rpu: null,
            rdc: null,
            rdp: null,
        },
        {
            week: 30,
            ekuitas: null,
            rpt: null,
            obligasi: 0.64,
            kas: 0.76,
            rpu: null,
            rdc: 0.55,
            rdp: null,
        },
        {
            week: 31,
            ekuitas: null,
            rpt: 0.68,
            obligasi: 0.74,
            kas: 0.78,
            rpu: 0.73,
            rdc: null,
            rdp: null,
        },
        {
            week: 32,
            ekuitas: null,
            rpt: null,
            obligasi: 0.76,
            kas: 0.75,
            rpu: 0.51,
            rdc: 0.86,
            rdp: null,
        },
        {
            week: 33,
            ekuitas: null,
            rpt: null,
            obligasi: 0.68,
            kas: 0.7,
            rpu: null,
            rdc: 0.75,
            rdp: null,
        },
        {
            week: 34,
            ekuitas: null,
            rpt: null,
            obligasi: 0.86,
            kas: 0.78,
            rpu: 0.55,
            rdc: 0.74,
            rdp: null,
        },
        {
            week: 35,
            ekuitas: null,
            rpt: null,
            obligasi: 0.68,
            kas: 0.78,
            rpu: null,
            rdc: 0.63,
            rdp: null,
        },
        {
            week: 36,
            ekuitas: null,
            rpt: null,
            obligasi: null,
            kas: 0.75,
            rpu: null,
            rdc: 0.76,
            rdp: null,
        },
        {
            week: 37,
            ekuitas: null,
            rpt: 0.56,
            obligasi: 0.69,
            kas: 0.74,
            rpu: 0.46,
            rdc: 0.86,
            rdp: null,
        },
        {
            week: 38,
            ekuitas: null,
            rpt: null,
            obligasi: 0.7,
            kas: 0.83,
            rpu: null,
            rdc: null,
            rdp: null,
        },
        {
            week: 39,
            ekuitas: null,
            rpt: null,
            obligasi: 0.66,
            kas: 0.79,
            rpu: null,
            rdc: 0.5,
            rdp: null,
        },
        {
            week: 40,
            ekuitas: null,
            rpt: null,
            obligasi: 0.66,
            kas: 0.79,
            rpu: null,
            rdc: 0.88,
            rdp: null,
        },
        {
            week: 41,
            ekuitas: null,
            rpt: null,
            obligasi: 0.78,
            kas: 0.78,
            rpu: null,
            rdc: null,
            rdp: null,
        },
        {
            week: 42,
            ekuitas: null,
            rpt: null,
            obligasi: 0.74,
            kas: 0.75,
            rpu: null,
            rdc: 0.69,
            rdp: null,
        },
        {
            week: 43,
            ekuitas: null,
            rpt: null,
            obligasi: 0.74,
            kas: 0.75,
            rpu: null,
            rdc: 0.69,
            rdp: null,
        },
        {
            week: 44,
            ekuitas: 0.85,
            rpt: null,
            obligasi: 0.74,
            kas: 0.81,
            rpu: 0.68,
            rdc: null,
            rdp: null,
        },
        {
            week: 45,
            ekuitas: null,
            rpt: null,
            obligasi: 0.74,
            kas: 0.85,
            rpu: 0.68,
            rdc: 0.79,
            rdp: null,
        },
        {
            week: 46,
            ekuitas: 0.88,
            rpt: null,
            obligasi: 0.74,
            kas: 0.85,
            rpu: 0.68,
            rdc: 0.79,
            rdp: null,
        },
        {
            week: 47,
            ekuitas: 0.86,
            rpt: null,
            obligasi: 0.74,
            kas: 0.82,
            rpu: 0.31,
            rdc: 0.44,
            rdp: null,
        },
        {
            week: 48,
            ekuitas: null,
            rpt: 0.54,
            obligasi: 0.74,
            kas: 0.71,
            rpu: null,
            rdc: 0.64,
            rdp: null,
        },
        {
            week: 49,
            ekuitas: null,
            rpt: null,
            obligasi: 0.74,
            kas: 0.75,
            rpu: null,
            rdc: 0.68,
            rdp: null,
        },
        {
            week: 50,
            ekuitas: null,
            rpt: null,
            obligasi: 0.68,
            kas: 0.54,
            rpu: 0.58,
            rdc: 0.65,
            rdp: null,
        },
        {
            week: 51,
            ekuitas: null,
            rpt: null,
            obligasi: 0.61,
            kas: 0.71,
            rpu: null,
            rdc: 0.51,
            rdp: null,
        },
        {
            week: 52,
            ekuitas: null,
            rpt: null,
            obligasi: null,
            kas: null,
            rpu: null,
            rdc: null,
            rdp: null,
        },
    ]
    }